version: '3.7'

services:
  postgres:
    container_name: postgres
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  goal-pet:
    container_name: goal-pet
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    depends_on:
      - postgres
    environment:
      SERVER_PORT: 8080
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: