spring:
  application:
    name: goal-pet
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000