spring:
  application:
    name: goal-pet
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

application:
  async:
    core-pool-size: 10
    max-pool-size: 50
    queue-capacity: 10000